from app.sensitive import sen

class Config:
    SQLALCHEMY_DATABASE_URI = sen.SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = sen.SQLALCHEMY_TRACK_MODIFICATIONS
    DEBUG = sen.DEBUG
    JWT_SECRET_KEY = sen.JWT_SECRET_KEY

    MAIL_SERVER = sen.MAIL_SERVER
    MAIL_PORT = sen.MAIL_PORT
    MAIL_USERNAME = sen.MAIL_USERNAME
    MAIL_PASSWORD = sen.MAIL_PASSWORD
    MAIL_USE_TLS = sen.MAIL_USE_TLS
    MAIL_USE_SSL = sen.MAIL_USE_SSL