"""empty message

Revision ID: 60dca74ad58e
Revises: 9ec756b03d38
Create Date: 2022-07-06 12:02:07.131952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dca74ad58e'
down_revision = '9ec756b03d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funcionario', type_='foreignkey')
    op.drop_column('funcionario', 'local')
    op.drop_constraint(None, 'produto', type_='foreignkey')
    op.drop_column('produto', 'local')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('local', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'produto', 'local', ['local'], ['id'])
    op.add_column('funcionario', sa.Column('local', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'funcionario', 'local', ['local'], ['id'])
    # ### end Alembic commands ###
