"""empty message

Revision ID: 936f7aa6ebfc
Revises: 6f5874a81902
Create Date: 2022-07-07 13:41:48.202927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936f7aa6ebfc'
down_revision = '6f5874a81902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cliente', 'senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cliente', 'endereco',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('encomenda', 'numero',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('encomenda', 'realizada',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('funcionario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('funcionario', 'senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('funcionario', 'cargo',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('funcionario', 'cadastrado',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('loja', 'espaco',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('produto', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('produto', 'preco',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('produto', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produto', 'quantidade',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('produto', 'preco',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('produto', 'nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('loja', 'espaco',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('funcionario', 'cadastrado',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('funcionario', 'cargo',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('funcionario', 'senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('funcionario', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('encomenda', 'realizada',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.alter_column('encomenda', 'numero',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cliente', 'endereco',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cliente', 'senha',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cliente', 'nome',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
