"""empty message

Revision ID: b797d11a1c11
Revises: 
Create Date: 2022-07-05 20:46:06.216900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b797d11a1c11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('solicitante', sa.String(length=30), nullable=True),
    sa.Column('realizada', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espaco', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('cadastrado', sa.String(length=1), nullable=True),
    sa.Column('local', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=30), nullable=True),
    sa.Column('demanda', sa.String(length=10), nullable=True),
    sa.Column('local', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['local'], ['local.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encomendas_e_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encomenda', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encomenda'], ['encomenda.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomendas_e_produtos')
    op.drop_table('produto')
    op.drop_table('funcionario')
    op.drop_table('local')
    op.drop_table('encomenda')
    # ### end Alembic commands ###
